language: cpp
script: $(CXX) -std=c++14 example.cpp Mix/*.cpp -o test && ./test
install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-5
  - export CXX="g++-5"
